FROM nginx:alpine

COPY src/crucible_engine/frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY src/crucible_engine/frontend/index.html /usr/share/nginx/html/
COPY src/crucible_engine/frontend/css/ /usr/share/nginx/html/css/
COPY src/crucible_engine/frontend/js/ /usr/share/nginx/html/js/
COPY src/crucible_engine/frontend/assets/ /usr/share/nginx/html/assets/

EXPOSE 80
